// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.blobs.pg.domain;

import com.malsolo.blobs.pg.domain.Documento;
import com.malsolo.blobs.pg.domain.DocumentoDataOnDemand;
import com.malsolo.blobs.pg.domain.DocumentoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DocumentoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DocumentoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DocumentoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DocumentoIntegrationTest: @Transactional;
    
    @Autowired
    private DocumentoDataOnDemand DocumentoIntegrationTest.dod;
    
    @Test
    public void DocumentoIntegrationTest.testCountDocumentoes() {
        Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", dod.getRandomDocumento());
        long count = Documento.countDocumentoes();
        Assert.assertTrue("Counter for 'Documento' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DocumentoIntegrationTest.testFindDocumento() {
        Documento obj = dod.getRandomDocumento();
        Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Documento' failed to provide an identifier", id);
        obj = Documento.findDocumento(id);
        Assert.assertNotNull("Find method for 'Documento' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Documento' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DocumentoIntegrationTest.testFindAllDocumentoes() {
        Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", dod.getRandomDocumento());
        long count = Documento.countDocumentoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Documento', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Documento> result = Documento.findAllDocumentoes();
        Assert.assertNotNull("Find all method for 'Documento' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Documento' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DocumentoIntegrationTest.testFindDocumentoEntries() {
        Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", dod.getRandomDocumento());
        long count = Documento.countDocumentoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Documento> result = Documento.findDocumentoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Documento' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Documento' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DocumentoIntegrationTest.testFlush() {
        Documento obj = dod.getRandomDocumento();
        Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Documento' failed to provide an identifier", id);
        obj = Documento.findDocumento(id);
        Assert.assertNotNull("Find method for 'Documento' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDocumento(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Documento' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DocumentoIntegrationTest.testMergeUpdate() {
        Documento obj = dod.getRandomDocumento();
        Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Documento' failed to provide an identifier", id);
        obj = Documento.findDocumento(id);
        boolean modified =  dod.modifyDocumento(obj);
        Integer currentVersion = obj.getVersion();
        Documento merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Documento' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DocumentoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", dod.getRandomDocumento());
        Documento obj = dod.getNewTransientDocumento(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Documento' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Documento' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Documento' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DocumentoIntegrationTest.testRemove() {
        Documento obj = dod.getRandomDocumento();
        Assert.assertNotNull("Data on demand for 'Documento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Documento' failed to provide an identifier", id);
        obj = Documento.findDocumento(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Documento' with identifier '" + id + "'", Documento.findDocumento(id));
    }
    
}
