// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.blobs.pg.domain;

import com.malsolo.blobs.pg.domain.NoDocumentoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NoDocumentoIntegrationTest_Roo_Configurable {
    
    declare @type: NoDocumentoIntegrationTest: @Configurable;
    
}
