// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.blobs.my.domain;

import com.malsolo.blobs.my.domain.DocumentIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DocumentIntegrationTest_Roo_Configurable {
    
    declare @type: DocumentIntegrationTest: @Configurable;
    
}
